# Generated by Django 4.2.13 on 2024-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_sell_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revised', 'Revised Offer')], max_length=20, null=True),
        ),
    ]
