# Generated by Django 4.2.13 on 2024-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_sell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='revised_offer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
